config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :employees
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:employee_index, :employee_name, :age, :designation, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :employee_index %>
    <%= form.number_field :employee_index, class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :employee_name %>
    <%= form.text_field :employee_name, class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :age %>
    <%= form.number_field :age ,class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :designation %>
    <%= form.text_field :designation, class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, class:"form-control", value: current_user.id, type: :hidden%>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>
</br>

  <%= link_to 'Show', @employee, class:"btn btn-secondary" %>
  <%= link_to 'Back', employees_path, class:"btn btn-secondary"%>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table class="table">
  <thead>
    <tr>
      <th>Employee index</th>
      <th>Employee name</th>
      <th>Age</th>
      <th>Designation</th>
      <% if user_signed_in? %>
      <th>User ID</th>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
     <% if employee.user == current_user%>
      <tr>
        <td><%= employee.employee_index %></td>
        <td><%= employee.employee_name %></td>
        <td><%= employee.age %></td>
        <td><%= employee.designation %></td>
        <td><%= employee.user_id %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path, class:"btn btn-secondary" %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee, class:"btn btn-secondary" %>
</br>
<%= link_to 'Back', employees_path , class:"btn btn-secondary"%>

app/views/employees/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello,<%= @employee.employee_name %></h1>
  <p class="lead">Welcome to the Employee Portal!</p>
  <hr class="my-4">
  <p id="notice"><%= notice %></p>

<p>
  <strong>Employee index:</strong>
  <%= @employee.employee_index %>
</p>

<p>
  <strong>Employee name:</strong>
  <%= @employee.employee_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employee.age %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @employee.designation %>
</p>
  <p class="lead">
    <%= link_to 'Edit', edit_employee_path(@employee), class:"btn btn-secondary" %> 
    <%= link_to 'Back', employees_path, class:"btn btn-secondary" %>
  </p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <div class="container-fluid">
    <!--<a class="navbar-brand" href="#">WebApp</a>-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'WebApp', root_path, class:"nav-link active"%>
          <!--<a class="nav-link active" aria-current="page" href="#">Home</a>-->
        </li>
        <li class="nav-item">
            <%= link_to 'About', home_about_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Employees', employees_path, class:"nav-link"%>
        </li>


        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Employees', new_employee_path, class:"nav-link"%>
          </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email  %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"dropdown-item" %>
            <!--<a class="dropdown-item" href="#">Action</a>-->
            <div class="dropdown-divider"></div>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            <!--<a class="dropdown-item" href="#">Sign Out</a>-->
          </div>
        </li>

        <% else %>

        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
        </li>
        <% end %>

      </ul>
      <form class="form-inline float-right">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container">
  <h1 class="display-4">About, employee portal!</h1>
  <p class="lead">Here you can add, delete and update employees!</p>
  <hr class="my-4">
  <p class="lead">
    <%= link_to "Let's Try", employees_path, class:"btn btn-secondary" %>
  </p>
</div>

app/views/home/index.html.erb
<div class="container">
  <h1 class="display-4">Greetings!</h1>
  <p class="lead">Welcome to the all new employee portal!</p>
  <hr class="my-4">
  <p>Completely setup using Ruby on Rails!</p>
  <p class="lead">
    <%= link_to 'Learn more', home_about_path,  class:"btn btn-secondary btn-lg"%>
  </p>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>WebApp</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container" style="margin: 2% auto;">
     <div class="jumbotron">
       <% if notice %>
        <%= render 'layouts/alerts' %>
       <% end %>

       <%= yield %>
     </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>